### ISSUE TITLE
Left control key is eaten by NodeEditorInputControls

### ISSUE THREAD

**Issue by molocai** [Seneral/Node_Editor_Framework#127]
Copying, pasting or selecting all (CTRL + C/V/A) are not working in node fields even after commenting out every static method using a HotkeyAttribute with KeyCode.LeftControl.

Anyone having the same problem?

**Comment by Seneral** [comment]
Hey, sorry for the super late reply, somehow slipped from my attention. 
Seems like HandleNodeSnap, the last method in NodeEditorInputControls, causes this. Removing the event.Use call should fix it, will do that soon:)

**Comment by Seneral** [comment]
Tried to fix it in the above commit, removing all potentially blocking controls (calls to Event.Use ()) but it seems to persist so the cause lies somewhere else. Still have to find out, may need some time...
Seneral

**Comment by Seneral** [comment]
Probably have to move it past the GUI (priority > 100).
Just and idea, will take a look again when I have time.

**Comment by Seneral** [comment]
Ok turned out it is not blocked by any control, but as the nodes uses the custom RTEditorGUI.FloatField for potential runtime uses, it does not support copy paste by default (relies on GUI.TextField).
Tos support this on all use cases, I added a generic copy paste functionality, which works perfectly fine (even at runtime) now:)

**Comment by Seneral** [comment]
Fixed:)
