### ISSUE TITLE
Multiple output into input knob

### ISSUE THREAD

**Issue by Aracasodius** [Seneral/Node_Editor_Framework#144]
Hello,

I'm looking for a way to be able to allow for multiple nodes to go into a single input knob. 
Has anyone figured this out, or is this implemented somehow? I saw a post on this already, but there was no actual clear instruction on how to do it. And it's marked as "Current focus"

So yeah, anyone any idea?

**Comment by Seneral** [comment]
Hey, do you use the master branch or the develop branch?
On master, this is not possible without workarounds like multiple input knobs.
On develop, there is a new connection system (among many other revamped systems), which abstracts the whole knob properties and allows you to create input knobs with multiple connections. One problem there is that the editing system does not allow for multi-multi connections yet, it needs a revamp to support that... So if you are going for single-multi instead of multi-single then it's good, multi-multi still don't work on the editing part:)
Seneral

**Comment by Aracasodius** [comment]
https://imgur.com/a/PQgo0

This is what i'm trying to acomplish, would this be doable right now with the developer branch?
Since I'm using the master branch and really need this new input system soon :p

**Comment by Seneral** [comment]
If the ability's output were to be limited to one connection, then yes:) Otherwise, not yet, due to editing reasons...
