### ISSUE TITLE
Node creation issues

### ISSUE THREAD

**Issue by aphex-** [Seneral/Node_Editor_Framework#72]
Hey,

If I open a _Node Editor_ window with an empty canvas the _Create_ method of all my custom _Nodes_ get called. I wonder why this happens on an empty canvas.
If I add a _Node_ by hand (right click => add) the _Create_ method is called as expected. Afterwards the methods _Calculate_ and _NodeGUI_ are called. The problem is that the _node.GetInstanceId()_ is changing between _Create_ and the other methods. This explains why I am loosing references to some custom private members that I set up in the _Create_ method. 
Is the _Node_ instance copied somewhere? Is this a bug or the expected behavior?

Sorry if this is not the right place for such questions..

**Comment by Seneral** [comment]
I it expected, it is somewhat of a weird implementation I admit, but it was a design choice I made back when I had less experience with C# (this project is now over a year old!).
I think I made this decision because I couldn't make the Create method static for some reason, probably because of inheritance and overriding, and so what I did was I created an 'invalid' default instance of each node on initialization (cringing when I think back), which will be used to create the other nodes. I agree this is is something I'd like to see changed in the future... xD

**Comment by Seneral** [comment]
Btw, the initial problem you described is fixed with 8b2caaa, Create is not called anymore on each initialization for each node.
The design issue is still existant though so I'll keep this open.

**Comment by Seneral** [comment]
Ok, finally completely eliminated with the latest modifications to the knob system and making the node property-based:)
